[api]
url = "http://localhost:3000/v1/api"

name = "name"
secret = "secret"

[api.endpoints]
authenticate = "/authenticate/system"
get_devices = "/servers/%d/devices"
update_device = "/devices/%d/ping"