workers = 4                     # number of workers probing hosts in paraller, list of hosts is distributed between workers
interval_between_tests = "1m"   # if defined, uping will probe devices in continous mode with specified intervals

[probe]
mode = "udp"
interval = "500ms"
timeout = "4s"
count = 10

[db]
driver = "postgres"
params = "postgres://login:pass@localhost/database"
id_server = 1

    [db.queries]
    # $1 means db.id_server
    get_devices =  "SELECT id, ip, inactive_since FROM devices WHERE id_server = $1"  

    # $1..$3 self explanatory, $4 id of tested device 
    update_device = "UPDATE devices SET loss = $1, average_time = $2, inactive_since = $3, test_date = NOW() WHERE id = $4"
    
[api]
url = "http://localhost:3000/v1/api"

name = "name"
secret = "secret"

    [api.endpoints]
    authenticate = "/authenticate/system"
    get_devices = "/servers/%d/devices"    # %d id of server, db.id_server
    update_device = "/devices/%d/ping"     # %d id of tested device